export const GET_UID = 'GET_UID'
export const ACTIVE_NAV = 'ACTIVE_NAV'
export const CREATE_NOTE = 'CREATE_NOTE'
export const CREATE_USER = 'CREATE_USER'
export const GET_DATA = 'GET_DATA'
export const SAVE_DATA = 'SAVE_DATA'
export const CHANGE_DATA = 'CHANGE_DATA'
export const UPDATE_MAIN_DATA = 'UPDATE_MAIN_DATA'
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE'
export const CHANGE_AUTH_STATE = 'CHANGE_AUTH_STATE'
export const CHANGE_BLOCK = 'CHANGE_BLOCK'

export const ADD_COORD_TO_DB = 'ADD_COORD_TO_DB'
export const ADD_IMG_TO_DB = 'ADD_IMG_TO_DB'

export const DELETE_COORDINATE = 'DELETE_COORDINATE'

export const DELETE_SLIDE = 'DELETE_SLIDE'